# Generated by Django 4.2.2 on 2023-11-23 13:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('code', models.CharField(auto_created=True, default=uuid.UUID('2ee9260e-aa60-471f-b5a1-df936b38038a'), max_length=255)),
                ('id', models.CharField(auto_created=True, default=uuid.UUID('73a22ce1-a244-47a2-8da6-c59d9447e53b'), max_length=250, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=250)),
                ('created_by', models.CharField(blank=True, max_length=250)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(max_length=50, null=True)),
                ('document_type', models.CharField(choices=[('C', 'Cedula'), ('P', 'Pasaporte'), ('J', 'RIF')], max_length=250, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('position', models.CharField(max_length=250, null=True)),
                ('primary_phone_number', models.CharField(max_length=250, null=True)),
                ('secondary_phone_number', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=250)),
                ('username', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
