# Generated by Django 4.2.2 on 2023-10-05 00:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(auto_created=True, default=uuid.UUID('8906c92a-cba7-46ca-bb3f-35dcab6ac973'), max_length=255)),
                ('email', models.EmailField(max_length=250)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
