# Generated by Django 4.2.2 on 2023-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('C', 'Cedula'), ('P', 'Pasaporte'), ('J', 'RIF')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(auto_created=True, default='bcrypt_sha256$$2b$12$XC7ARFbgcYZF72xaujofH.e07aEOPRb9/kqW6gRHTJg8f4BIUMIKi', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_phone_number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_phone_number',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
