# Generated by Django 4.2.2 on 2023-10-05 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(auto_created=True, default=uuid.UUID('3326700f-d7f2-4a33-833a-e140f6188c44'), max_length=255),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.CharField(default=uuid.UUID('1c88985f-fe3d-48f6-8568-13c21b4fe42a'), max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
