# Generated by Django 4.2.2 on 2023-10-05 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_invitation_code_alter_invitation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='created_by',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(auto_created=True, default=uuid.UUID('c986f746-4ae1-44a4-9fb7-d9fc98f13076'), max_length=255),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.CharField(auto_created=True, default=uuid.UUID('2eda30f6-76f9-4659-98ce-a5ff0e7db5c2'), max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
